server: 
  port: 9001 #启动端口
eureka:
  client:
    service-url:
           defaultZone: http://localhost:10001/eureka
spring: 
  application:
    name: Spring-Cloud-Config #配置服务名称
  cloud: 
    config: 
      server: 
        git: 
          uri: https://github.com/TimiQ/spring-cloud-demo.git #获取配置的git地址
          search-paths: config #搜索的配置路径
      label: master
  zipkin:
    base-url: http://localhost:9411