loginUsername: root
loginPassword: 123456
spring:
  datasource:
    url: jdbc:mysql://192.168.24.29:3306/IMS?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: admin
    password: Admin123@
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
    #RabbitMQ 消息
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
#Eureka服务注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
#Mybatis配置 
mybatis:
  mapper-locations: classpath:com/pcd/springcloud/mapper/*.xml
  type-aliases-package: com.pcd.springcloud.model
