spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  zipkin:
    base-url: http://localhost:9411
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
