spring:
  #RabbitMQ 消息
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
#Eureka服务注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: Spring-Cloud-Ribbon
    api-b:
      path: /api-b/**
      serviceId: Spring-Cloud-Web
