spring:
  rabbitmq:
    host:localhost
    port:5672
    username:admin
    password:admin
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
